# Generated by Django 6.0.6 on 2026-07-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('support', 'Специалист'), ('manager', 'Менеджер')], default='employee', max_length=20),
        ),
    ]
